### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by Lost-Season** [Yuer-QAQ/Grasscutter-Plugin#2]
## GIMI-3DMigoto
* [开源地址&教程](https://github.com/SilentNightSound/GI-Model-Importer)
* [mod论坛地址](https://gamebanana.com/mods/games/8552)
* [github上的mod地址](https://github.com/SilentNightSound/GI-Model-Importer-Assets)
## SpecialK
* [开源地址](https://github.com/SpecialKO/SpecialK)
* [英文wiki（教程）](https://github.com/zeroruka/GI-SKMods/wiki)
* [中文wiki（教程）](https://github.com/zeroruka/GI-SKMods-wiki/wiki)
* [mod地址](https://github.com/zeroruka/GI-SKMods)
## melonloader（原则上不再更新）
* [适用于2.6（客户端）](https://github.com/lassedds/Melonloader-AnimeGaming)
* [升级到3.0（客户端）](https://github.com/Taiga74164/ChecksumBypass-GenshinImpact)（注入dll文件）
* [mod地址&教程](https://github.com/zeroruka/GI-Assets/tree/main/Mods/Scripts)

**Comment by Yuer-QAQ** [comment]
1
